-- ===========================================================================
-- VITARAIZ - MIGRACIÓN ESQUEMA SALESAPP
-- Parte 09/09: DATOS — PAGOS, FOTOS, RUTAS, ACCIONES Y AUDITORÍA
-- Tablas: COLLECTOR_ROUTES, COLLECTOR_VISIT_ACTIONS, PAYMENTS,
--         PAYMENT_PHOTOS, AUDIT_LOGS
-- Generado: 2026-04-03
-- ===========================================================================
SET DEFINE OFF;

-- ---------------------------------------------------------------------------
-- COLLECTOR_ROUTES (2 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.COLLECTOR_ROUTES (ROUTE_ID,COLLECTOR_ID,ROUTE_DATE,SALES_ASSIGNED,SALES_VISITED,TOTAL_COLLECTED,STATUS) VALUES (1,2,TO_DATE('2026-03-23','YYYY-MM-DD'),5,3,755,'ACTIVE');
INSERT INTO SALESAPP.COLLECTOR_ROUTES (ROUTE_ID,COLLECTOR_ID,ROUTE_DATE,SALES_ASSIGNED,SALES_VISITED,TOTAL_COLLECTED,STATUS) VALUES (2,4,TO_DATE('2026-03-23','YYYY-MM-DD'),3,2,866.66,'ACTIVE');
COMMIT;

-- ---------------------------------------------------------------------------
-- COLLECTOR_VISIT_ACTIONS (2 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.COLLECTOR_VISIT_ACTIONS (ACTION_ID,SALE_ID,COLLECTOR_ID,ACTION_TYPE,ACTION_DATE,GPS_LATITUDE,GPS_LONGITUDE,NOTES) VALUES (3,10007,2,'VISITADO',TO_DATE('2026-03-23','YYYY-MM-DD'),19.432082,-99.133209,'Cliente atendido, pago recibido');
INSERT INTO SALESAPP.COLLECTOR_VISIT_ACTIONS (ACTION_ID,SALE_ID,COLLECTOR_ID,ACTION_TYPE,ACTION_DATE,GPS_LATITUDE,GPS_LONGITUDE,NOTES) VALUES (4,10003,2,'MAS_TARDE',TO_DATE('2026-03-23','YYYY-MM-DD'),19.43512,-99.13589,'Cliente no estaba, regresar después');
COMMIT;

-- ---------------------------------------------------------------------------
-- PAYMENTS (16 registros)
-- STATUS: 1=PENDING, 2=CONFIRMADO
-- COLLECTION_ACTION_ID: 10=PAGO_RECIBIDO
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40009,10004,2,TO_DATE('2026-03-17','YYYY-MM-DD'),420,'CASH',19.43789,-99.1321,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40010,10007,2,TO_DATE('2026-02-22','YYYY-MM-DD'),167.5,'CASH',19.432082,-99.133209,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40011,10007,2,TO_DATE('2026-03-01','YYYY-MM-DD'),167.5,'CASH',19.432082,-99.133209,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40012,10007,2,TO_DATE('2026-03-08','YYYY-MM-DD'),167.5,'CASH',19.432082,-99.133209,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40013,10007,2,TO_DATE('2026-03-15','YYYY-MM-DD'),167.5,'CASH',19.432082,-99.133209,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40014,10003,2,TO_DATE('2026-02-27','YYYY-MM-DD'),350,'CASH',19.43512,-99.13589,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40015,10003,2,TO_DATE('2026-03-06','YYYY-MM-DD'),350,'CASH',19.43512,-99.13589,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40016,10004,4,TO_DATE('2026-03-08','YYYY-MM-DD'),433.33,'CASH',19.42891,-99.14023,'DEVICE-ANA-002',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40017,10004,4,TO_DATE('2026-03-15','YYYY-MM-DD'),433.33,'CASH',19.42891,-99.14023,'DEVICE-ANA-002',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40018,10004,4,TO_DATE('2026-03-22','YYYY-MM-DD'),433.33,'CASH',19.42891,-99.14023,'DEVICE-ANA-002',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40019,10006,2,TO_DATE('2026-03-22','YYYY-MM-DD'),420,'CASH',19.43789,-99.1321,'DEVICE-PEDRO-001',NULL,'1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40020,10007,2,TO_DATE('2026-03-23','YYYY-MM-DD'),100,'CASH',19.432082,-99.133209,'TEST-DEVICE','Pago de prueba del paquete','1',NULL,NULL,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40124,10023,2,TO_DATE('2026-04-01','YYYY-MM-DD'),100,'CASH',19.2566467,-98.900301,'WEB_API',NULL,'1',NULL,10,NULL,1);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40125,10023,2,TO_DATE('2026-04-01','YYYY-MM-DD'),100,'CASH',19.2566928,-98.9002773,'WEB_API',NULL,'1',NULL,10,NULL,1);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40126,10023,2,TO_DATE('2026-04-01','YYYY-MM-DD'),200,'CASH',19.2566966,-98.9002782,'WEB_API',NULL,'1',NULL,10,NULL,2);
INSERT INTO SALESAPP.PAYMENTS (PAYMENT_ID,SALE_ID,COLLECTOR_ID,PAYMENT_DATE,AMOUNT,PAYMENT_METHOD,GPS_LATITUDE,GPS_LONGITUDE,DEVICE_ID,NOTES,SYNCED,UPDATED_BY,COLLECTION_ACTION_ID,COLLECTION_SUB_ID,STATUS) VALUES (40140,10060,2,TO_DATE('2026-04-02','YYYY-MM-DD'),200,'CASH',19.2567019,-98.9002771,'WEB_API',NULL,'1',NULL,10,NULL,1);
COMMIT;

-- ---------------------------------------------------------------------------
-- PAYMENT_PHOTOS (12 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (10,40009,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\17\payment_40009_receipt.jpg',NULL,19.43789,-99.1321,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (11,40010,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\02\22\payment_40010_receipt.jpg',NULL,19.432082,-99.133209,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (12,40011,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\01\payment_40011_receipt.jpg',NULL,19.432082,-99.133209,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (13,40012,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\08\payment_40012_receipt.jpg',NULL,19.432082,-99.133209,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (14,40013,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\15\payment_40013_receipt.jpg',NULL,19.432082,-99.133209,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (15,40014,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\02\27\payment_40014_receipt.jpg',NULL,19.43512,-99.13589,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (16,40015,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\06\payment_40015_receipt.jpg',NULL,19.43512,-99.13589,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (17,40016,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\08\payment_40016_receipt.jpg',NULL,19.42891,-99.14023,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (18,40017,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\15\payment_40017_receipt.jpg',NULL,19.42891,-99.14023,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (19,40018,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\22\payment_40018_receipt.jpg',NULL,19.42891,-99.14023,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (20,40019,'RECEIPT','G:\AppData\SalesPhotos\Payments\2026\03\22\payment_40019_receipt.jpg',NULL,19.43789,-99.1321,NULL);
INSERT INTO SALESAPP.PAYMENT_PHOTOS (PHOTO_ID,PAYMENT_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE) VALUES (21,40020,'RECEIPT','G:\TEST\payment_test.jpg',NULL,19.432082,-99.133209,NULL);
COMMIT;

-- ---------------------------------------------------------------------------
-- AUDIT_LOGS (49 registros — TRG_SALES_AUDIT generará nuevos en la BD destino)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (1,NULL,'SALES',10007,'UPDATE','status=EN_PROCESO,amount=1340');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (2,2,'PAYMENT',40020,'INSERT','Pago: $100');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (3,1,'CUSTOMER',1008,'INSERT','Cliente: Cliente de Prueba Paquete');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (4,3,'SALE',10008,'INSERT','Venta: $5000');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (5,1,'CUSTOMER',1000,'MARK_GOLD','Gold customer');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (21,NULL,'CUSTOMER',1041,'INSERT','Cliente: esteban');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (22,1,'SALE',10020,'INSERT','Venta registrada');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (23,NULL,'SALES',10020,'UPDATE','status=POR_INICIAR,amount=450');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (24,NULL,'CUSTOMER',1042,'INSERT','Cliente: x este');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (25,1,'SALE',10021,'INSERT','Venta registrada');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (26,NULL,'SALES',10021,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (27,NULL,'CUSTOMER',1043,'INSERT','Cliente: x este');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (28,1,'SALE',10022,'INSERT','Venta registrada');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (29,NULL,'SALES',10022,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (30,NULL,'CUSTOMER',1044,'INSERT','Cliente: x este');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (31,1,'SALE',10023,'INSERT','Venta registrada');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (32,NULL,'SALES',10023,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (41,NULL,'SALES',10021,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (42,NULL,'SALES',10020,'UPDATE','status=POR_INICIAR,amount=450');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (43,NULL,'SALES',10022,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (44,NULL,'SALES',10023,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (45,2,'CUSTOMER',1060,'INSERT','Cliente registrado: esteban ga gab');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (46,2,'CUSTOMER',1061,'INSERT','Cliente registrado: esteban ga gab');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (61,1,'CUSTOMER',1080,'INSERT','Cliente registrado: x este 2029');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (62,1,'SALE',10040,'INSERT','Venta registrada | Plazo: SEMANAL | Dia cobro: LUN | Enganche: $2');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (63,NULL,'SALES',10040,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (81,2,'PAYMENT',40124,'INSERT','Pago: $100');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (82,2,'PAYMENT',40125,'INSERT','Pago: $100');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (83,2,'PAYMENT',40126,'INSERT','Pago: $200');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (84,3,'CUSTOMER',1100,'INSERT','Cliente registrado: x este 2029');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (85,3,'SALE',10060,'INSERT','Venta registrada | Plazo: MENSUAL | Dia cobro: LUN | Enganche: $300');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (86,NULL,'SALES',10060,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (87,3,'CUSTOMER',1101,'INSERT','Cliente registrado: 99 k');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (88,3,'SALE',10061,'INSERT','Venta registrada | Plazo: MENSUAL | Dia cobro: JUE | Enganche: $123');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (89,NULL,'SALES',10061,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (90,3,'CUSTOMER',1102,'INSERT','Cliente registrado: 99 k 88');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (91,3,'SALE',10062,'INSERT','Venta registrada | Plazo: QUINCENAL | Dia cobro: VIE | Enganche: $123');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (92,NULL,'SALES',10062,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (93,NULL,'SALES',10062,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (94,NULL,'CUSTOMER',1102,'UPDATE','Cliente actualizado: * esteban *');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (95,NULL,'CUSTOMER',1102,'UPDATE','Cliente actualizado: @ esteban @');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (101,NULL,'SALES',10061,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (102,NULL,'CUSTOMER',1101,'UPDATE','Cliente actualizado: **** ## EAG ##');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (103,NULL,'SALES',10060,'UPDATE','status=POR_INICIAR,amount=890');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (104,NULL,'CUSTOMER',1100,'UPDATE','Cliente actualizado: *****1******');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (105,2,'PAYMENT',40140,'INSERT','Pago: $200');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (106,5,'CUSTOMER',1120,'INSERT','Cliente registrado: ESTEBAN 999 -');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (107,5,'SALE',10080,'INSERT','Venta registrada | Plazo: SEMANAL | Dia cobro: MAR | Enganche: $123');
INSERT INTO SALESAPP.AUDIT_LOGS (LOG_ID,USER_ID,TABLE_NAME,RECORD_ID,ACTION,NEW_VALUES) VALUES (108,NULL,'SALES',10080,'UPDATE','status=POR_INICIAR,amount=450');
COMMIT;

SET DEFINE ON;
