-- ===========================================================================
-- VITARAIZ - MIGRACIÓN ESQUEMA SALESAPP
-- Parte 08/09: DATOS — USUARIOS, PRODUCTOS, CLIENTES, VENTAS
-- Tablas: USERS, PRODUCT_CATEGORIES, PRODUCTS, CUSTOMERS,
--         SALES, SALE_ITEMS, SALE_PHOTOS
-- Generado: 2026-04-03
-- ===========================================================================
SET DEFINE OFF;

-- ---------------------------------------------------------------------------
-- USERS (5 registros)
-- NOTA: PASSWORD_HASH contiene contraseñas en texto claro de prueba.
--       En producción real reemplazar con hashes BCrypt.
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.USERS (USER_ID,USERNAME,PASSWORD_HASH,FULL_NAME,EMAIL,PHONE,ROLE_ID,ZONE_ID,SUPERVISOR_ID,IS_ACTIVE) VALUES (1,'admin','Admin2026!','Administrador Sistema','admin@salesapp.com','555-0001',8,NULL,NULL,'1');
INSERT INTO SALESAPP.USERS (USER_ID,USERNAME,PASSWORD_HASH,FULL_NAME,EMAIL,PHONE,ROLE_ID,ZONE_ID,SUPERVISOR_ID,IS_ACTIVE) VALUES (2,'pedro','Pedro2026!','Pedro Gómez Cobrador','pedro.gomez@salesapp.com','555-0002',4,1,NULL,'1');
INSERT INTO SALESAPP.USERS (USER_ID,USERNAME,PASSWORD_HASH,FULL_NAME,EMAIL,PHONE,ROLE_ID,ZONE_ID,SUPERVISOR_ID,IS_ACTIVE) VALUES (3,'veronica','Veronica2026!','Laura Martínez Vendedora','laura.martinez@salesapp.com','555-0003',1,1,NULL,'1');
INSERT INTO SALESAPP.USERS (USER_ID,USERNAME,PASSWORD_HASH,FULL_NAME,EMAIL,PHONE,ROLE_ID,ZONE_ID,SUPERVISOR_ID,IS_ACTIVE) VALUES (4,'ana','Ana2026!','Ana Silva Cobradora','ana.silva@salesapp.com','555-0004',4,2,NULL,'1');
INSERT INTO SALESAPP.USERS (USER_ID,USERNAME,PASSWORD_HASH,FULL_NAME,EMAIL,PHONE,ROLE_ID,ZONE_ID,SUPERVISOR_ID,IS_ACTIVE) VALUES (5,'supervisor','Super2026!','Carlos Ruiz Supervisor','carlos.ruiz@salesapp.com','555-0005',6,NULL,NULL,'1');
COMMIT;

-- ---------------------------------------------------------------------------
-- PRODUCT_CATEGORIES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PRODUCT_CATEGORIES (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION) VALUES (1,'Electrodomésticos','Productos para el hogar');
INSERT INTO SALESAPP.PRODUCT_CATEGORIES (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION) VALUES (2,'Electrónica','Dispositivos electrónicos');
INSERT INTO SALESAPP.PRODUCT_CATEGORIES (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION) VALUES (3,'Muebles','Muebles para el hogar');
COMMIT;

-- ---------------------------------------------------------------------------
-- PRODUCTS
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (100,'PROD-001','Licuadora Premium','Licuadora 10 velocidades',1,450,50,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (101,'PROD-002','Microondas Digital','Microondas 1.5 pies',1,890,30,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (102,'PROD-003','Tablet Android 10"','Tablet 64GB',2,1200,25,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (103,'PROD-004','Smart TV 43"','Televisor LED Full HD',2,3500,15,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (104,'PROD-005','Juego de Sala 3 Piezas','Sala completa',3,5200,10,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (105,'PROD-006','Comedor 6 Personas','Mesa y 6 sillas',3,4800,8,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (106,'PROD-007','Refrigerador 18 pies','Refrigerador doble puerta',1,6500,12,'1');
INSERT INTO SALESAPP.PRODUCTS (PRODUCT_ID,PRODUCT_CODE,PRODUCT_NAME,DESCRIPTION,CATEGORY_ID,UNIT_PRICE,STOCK_QUANTITY,IS_ACTIVE) VALUES (107,'PROD-008','Lavadora 18kg','Lavadora automática',1,4200,18,'1');
COMMIT;

-- ---------------------------------------------------------------------------
-- CUSTOMERS (20 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1000,'Juan Pérez García','555-1002','juan.perez@email.com','Av. Insurgentes #456','Frente al parque central',19.43512,-99.13589,1,'0','1',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1001,'Carlos Ruiz Sánchez','555-1003','carlos.ruiz@email.com','Calle 12 #789','A un lado del supermercado',19.42891,-99.14023,2,'0','1',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1002,'Sofia Torres Ramírez','555-1004','sofia.torres@email.com','Av. Reforma #234','Esquina con Calle 8',19.43145,-99.1389,2,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1003,'Luis González Morales','555-1005','luis.gonzalez@email.com','Calle 20 #567','Casa azul con reja blanca',19.43789,-99.1321,1,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1004,'Elena Hernández Díaz','555-1006','elena.hernandez@email.com','Av. Universidad #890','Al lado de la farmacia',19.42034,-99.14567,3,'0','1',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1005,'Roberto Silva Martínez','555-1007','roberto.silva@email.com','Calle 15 #321','Portón verde',19.42567,-99.12045,4,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1006,'Patricia Morales Flores','555-1008','patricia.morales@email.com','Av. Hidalgo #654','Cerca del mercado',19.43452,-99.15089,5,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1007,'María López Hernández','555-1001','maria.lopez@email.com','Calle 5 #123, Col. Centro','Entre Av. Principal y Calle 4',19.432082,-99.133209,1,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1008,'Cliente de Prueba Paquete','555-9999','prueba@paquete.com','Calle Prueba 123',NULL,19.43,-99.13,1,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1041,'esteban','333',NULL,'22, entre 22 y 22, ref: 222',NULL,19.256888,-98.900194,4,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1042,'x este','222',NULL,'222, entre 22 y 22, ref: 222',NULL,19.256902,-98.900186,4,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1043,'x este','222',NULL,'222, entre 22 y 22, ref: 222',NULL,19.256902,-98.900186,4,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1044,'x este','222',NULL,'222, entre 22 y 22, ref: 222',NULL,19.256902,-98.900186,4,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1060,'esteban ga gab','222',NULL,'aaaa, entre 23 y 23, ref: aaaa',NULL,19.256903,-98.900171,4,'0','0',2);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1061,'esteban ga gab','222',NULL,'aaaa, entre 23 y 23, ref: aaaa',NULL,19.256903,-98.900171,4,'0','0',2);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1080,'x este 2029','222',NULL,'222, entre 22 y 22, ref: 222',NULL,19.256902,-98.900186,4,'0','0',1);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1100,'*****1******','8989898988',NULL,'222, entre 22 y 22, ref: 222',NULL,19.256902,-98.900186,3,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1101,'**** ## EAG ##','222222',NULL,'we, entre 1 y 1, ref: 23',NULL,19.256696,-98.900279,1,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1102,'@ esteban @','222222',NULL,'we, entre 1 y 1, ref: 23',NULL,19.256696,-98.900279,1,'0','0',3);
INSERT INTO SALESAPP.CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME,PHONE,EMAIL,ADDRESS,ADDRESS_REF,GPS_LATITUDE,GPS_LONGITUDE,ZONE_ID,IS_BLACKLISTED,IS_GOLD_CUSTOMER,CREATED_BY) VALUES (1120,'ESTEBAN 999 -','2255564545',NULL,'111, entre 111 y 111, ref: 2332',NULL,19.256698,-98.900279,1,'0','0',5);
COMMIT;

-- ---------------------------------------------------------------------------
-- SALES (15 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10003,1000,3,TO_DATE('2026-02-20','YYYY-MM-DD'),3500,'WEEKLY',10,350,'EN_PROCESO',2,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10004,1001,3,TO_DATE('2026-03-01','YYYY-MM-DD'),5200,'WEEKLY',12,433.33,'EN_PROCESO',4,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10005,1002,3,TO_DATE('2026-03-10','YYYY-MM-DD'),6500,'WEEKLY',15,433.33,'POR_INICIAR',4,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10006,1003,3,TO_DATE('2026-03-15','YYYY-MM-DD'),4200,'WEEKLY',10,420,'EN_PROCESO',2,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10007,1007,3,TO_DATE('2026-02-15','YYYY-MM-DD'),1340,'WEEKLY',8,167.5,'EN_PROCESO',2,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10008,1000,3,TO_DATE('2026-03-23','YYYY-MM-DD'),5000,'WEEKLY',10,500,'POR_INICIAR',2,NULL,'SEMANAL',NULL,NULL,0);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10020,1041,1,TO_DATE('2026-03-26','YYYY-MM-DD'),450,'30 días',NULL,NULL,'POR_INICIAR',NULL,'Estatus: LIQUIDADO | Cobro: MIE | FechaPrimerCobro: 26/03/2026 | Enganche: 122.00 | 123w','SEMANAL','MIE',TO_DATE('2026-03-26','YYYY-MM-DD'),122);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10021,1042,1,TO_DATE('2026-03-26','YYYY-MM-DD'),890,'7 días',NULL,NULL,'POR_INICIAR',NULL,'Estatus: POR INICIAR | Cobro: LUN | FechaPrimerCobro: 26/03/2026 | Enganche: 2.00 | qqq','SEMANAL','LUN',TO_DATE('2026-03-26','YYYY-MM-DD'),2);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10022,1043,1,TO_DATE('2026-03-26','YYYY-MM-DD'),890,'7 días',NULL,NULL,'POR_INICIAR',NULL,'Estatus: POR INICIAR | Cobro: LUN | FechaPrimerCobro: 26/03/2026 | Enganche: 2.00 | qqq','SEMANAL','LUN',TO_DATE('2026-03-26','YYYY-MM-DD'),2);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10023,1044,1,TO_DATE('2026-03-26','YYYY-MM-DD'),890,'7 días',NULL,NULL,'POR_INICIAR',NULL,'Estatus: POR INICIAR | Cobro: LUN | FechaPrimerCobro: 26/03/2026 | Enganche: 2.00 | qqq','SEMANAL','LUN',TO_DATE('2026-03-26','YYYY-MM-DD'),2);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10040,1080,1,TO_DATE('2026-03-28','YYYY-MM-DD'),890,'7 dias',7,NULL,'POR_INICIAR',NULL,'Estatus: POR INICIAR | Cobro: LUN | FechaPrimerCobro: 26/03/2026 | Enganche: 2.00 | qqq','SEMANAL','LUN',TO_DATE('2026-03-26','YYYY-MM-DD'),2);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10060,1100,3,TO_DATE('2026-04-01','YYYY-MM-DD'),890,'30 dias',30,NULL,'POR_INICIAR',NULL,'@','CONTADO','LUN',TO_DATE('2026-03-18','YYYY-MM-DD'),300);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10061,1101,3,TO_DATE('2026-04-01','YYYY-MM-DD'),890,'30 dias',30,NULL,'POR_INICIAR',NULL,'@@@','MENSUAL','JUE',TO_DATE('2026-04-01','YYYY-MM-DD'),123);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10062,1102,3,TO_DATE('2026-04-01','YYYY-MM-DD'),890,'15 dias',15,NULL,'POR_INICIAR',NULL,'@@@ # QQQ','QUINCENAL','VIE',TO_DATE('2026-04-01','YYYY-MM-DD'),123);
INSERT INTO SALESAPP.SALES (SALE_ID,CUSTOMER_ID,SELLER_ID,SALE_DATE,TOTAL_AMOUNT,PAYMENT_TERMS,NUMBER_OF_PAYMENTS,PAYMENT_AMOUNT,STATUS,ASSIGNED_COLLECTOR_ID,NOTES,PAYMENT_TERM,COLLECTION_DAY,FIRST_COLLECTION_DATE,DOWN_PAYMENT) VALUES (10080,1120,5,TO_DATE('2026-04-02','YYYY-MM-DD'),450,'7 dias',7,NULL,'POR_INICIAR',NULL,'21q212q12q1q2q','SEMANAL','MAR',TO_DATE('2026-04-02','YYYY-MM-DD'),123);
COMMIT;

-- ---------------------------------------------------------------------------
-- SALE_ITEMS (16 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (7,10003,103,1,3500,3500,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (8,10004,104,1,5200,5200,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (9,10005,106,1,6500,6500,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (10,10006,107,1,4200,4200,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (11,10007,100,1,450,450,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (12,10007,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (13,10008,100,2,450,900,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (21,10020,100,1,450,450,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (22,10021,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (23,10022,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (24,10023,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (41,10040,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (61,10060,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (62,10061,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (63,10062,101,1,890,890,0,NULL);
INSERT INTO SALESAPP.SALE_ITEMS (SALE_ITEM_ID,SALE_ID,PRODUCT_ID,QUANTITY,UNIT_PRICE,SUBTOTAL,DISCOUNT,NOTES) VALUES (81,10080,100,1,450,450,0,NULL);
COMMIT;

-- ---------------------------------------------------------------------------
-- SALE_PHOTOS (15 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (16,10003,'FOTO_FACHADA','G:\AppData\SalesPhotos\Ventas\2026\02\20\sale_10003_fachada.jpg',NULL,19.43512,-99.13589,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (17,10003,'FOTO_CLIENTE','G:\AppData\SalesPhotos\Ventas\2026\02\20\sale_10003_cliente.jpg',NULL,19.43512,-99.13589,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (18,10003,'FOTO_CONTRATO','G:\AppData\SalesPhotos\Ventas\2026\02\20\sale_10003_contrato.jpg',NULL,19.43512,-99.13589,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (19,10004,'FOTO_FACHADA','G:\AppData\SalesPhotos\Ventas\2026\03\01\sale_10004_fachada.jpg',NULL,19.42891,-99.14023,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (20,10004,'FOTO_CLIENTE','G:\AppData\SalesPhotos\Ventas\2026\03\01\sale_10004_cliente.jpg',NULL,19.42891,-99.14023,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (21,10004,'FOTO_CONTRATO','G:\AppData\SalesPhotos\Ventas\2026\03\01\sale_10004_contrato.jpg',NULL,19.42891,-99.14023,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (22,10005,'FOTO_FACHADA','G:\AppData\SalesPhotos\Ventas\2026\03\10\sale_10005_fachada.jpg',NULL,19.43145,-99.1389,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (23,10005,'FOTO_CLIENTE','G:\AppData\SalesPhotos\Ventas\2026\03\10\sale_10005_cliente.jpg',NULL,19.43145,-99.1389,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (24,10005,'FOTO_CONTRATO','G:\AppData\SalesPhotos\Ventas\2026\03\10\sale_10005_contrato.jpg',NULL,19.43145,-99.1389,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (25,10006,'FOTO_FACHADA','G:\AppData\SalesPhotos\Ventas\2026\03\15\sale_10006_fachada.jpg',NULL,19.43789,-99.1321,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (26,10006,'FOTO_CLIENTE','G:\AppData\SalesPhotos\Ventas\2026\03\15\sale_10006_cliente.jpg',NULL,19.43789,-99.1321,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (27,10006,'FOTO_CONTRATO','G:\AppData\SalesPhotos\Ventas\2026\03\15\sale_10006_contrato.jpg',NULL,19.43789,-99.1321,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (28,10007,'FOTO_FACHADA','G:\AppData\SalesPhotos\Ventas\2026\02\15\sale_10007_fachada.jpg',NULL,19.432082,-99.133209,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (29,10007,'FOTO_CLIENTE','G:\AppData\SalesPhotos\Ventas\2026\02\15\sale_10007_cliente.jpg',NULL,19.432082,-99.133209,NULL,3,'1');
INSERT INTO SALESAPP.SALE_PHOTOS (PHOTO_ID,SALE_ID,PHOTO_TYPE,FILE_PATH,THUMBNAIL_PATH,GPS_LATITUDE,GPS_LONGITUDE,FILE_SIZE,UPLOADED_BY,SYNCED) VALUES (30,10007,'FOTO_CONTRATO','G:\AppData\SalesPhotos\Ventas\2026\02\15\sale_10007_contrato.jpg',NULL,19.432082,-99.133209,NULL,3,'1');
COMMIT;

SET DEFINE ON;
