-- ===========================================================================
-- VITARAIZ - MIGRACIÓN ESQUEMA SALESAPP
-- Parte 05/09: ÍNDICES SECUNDARIOS (IDX_*)
-- Las PK y UK ya fueron creadas como constraints en los CREATE TABLE
-- Generado: 2026-04-03
-- ===========================================================================

-- AUDIT_LOGS
CREATE INDEX SALESAPP.IDX_AUDIT_USER      ON SALESAPP.AUDIT_LOGS (USER_ID);
CREATE INDEX SALESAPP.IDX_AUDIT_TABLE     ON SALESAPP.AUDIT_LOGS (TABLE_NAME);
CREATE INDEX SALESAPP.IDX_AUDIT_TIMESTAMP ON SALESAPP.AUDIT_LOGS (TIMESTAMP);

-- COLLECTOR_ROUTES
CREATE INDEX SALESAPP.IDX_ROUTES_COLLECTOR ON SALESAPP.COLLECTOR_ROUTES (COLLECTOR_ID);
CREATE INDEX SALESAPP.IDX_ROUTES_DATE      ON SALESAPP.COLLECTOR_ROUTES (ROUTE_DATE);

-- COLLECTOR_VISIT_ACTIONS
CREATE INDEX SALESAPP.IDX_ACTIONS_SALE      ON SALESAPP.COLLECTOR_VISIT_ACTIONS (SALE_ID);
CREATE INDEX SALESAPP.IDX_ACTIONS_COLLECTOR ON SALESAPP.COLLECTOR_VISIT_ACTIONS (COLLECTOR_ID);
CREATE INDEX SALESAPP.IDX_ACTIONS_DATE      ON SALESAPP.COLLECTOR_VISIT_ACTIONS (ACTION_DATE);

-- CUSTOMERS
CREATE INDEX SALESAPP.IDX_CUSTOMERS_ZONE      ON SALESAPP.CUSTOMERS (ZONE_ID);
CREATE INDEX SALESAPP.IDX_CUSTOMERS_NAME      ON SALESAPP.CUSTOMERS (CUSTOMER_NAME);
CREATE INDEX SALESAPP.IDX_CUSTOMERS_BLACKLIST ON SALESAPP.CUSTOMERS (IS_BLACKLISTED);
CREATE INDEX SALESAPP.IDX_CUSTOMERS_GOLD      ON SALESAPP.CUSTOMERS (IS_GOLD_CUSTOMER);

-- CUSTOMER_INCIDENTS
CREATE INDEX SALESAPP.IDX_INCIDENTS_CUSTOMER ON SALESAPP.CUSTOMER_INCIDENTS (CUSTOMER_ID);
CREATE INDEX SALESAPP.IDX_INCIDENTS_DATE      ON SALESAPP.CUSTOMER_INCIDENTS (REPORTED_AT);

-- PAYMENTS
CREATE INDEX SALESAPP.IDX_PAYMENTS_SALE      ON SALESAPP.PAYMENTS (SALE_ID);
CREATE INDEX SALESAPP.IDX_PAYMENTS_COLLECTOR ON SALESAPP.PAYMENTS (COLLECTOR_ID);
CREATE INDEX SALESAPP.IDX_PAYMENTS_DATE      ON SALESAPP.PAYMENTS (PAYMENT_DATE);

-- PAYMENT_PHOTOS
CREATE INDEX SALESAPP.IDX_PAYMENT_PHOTOS_PAYMENT ON SALESAPP.PAYMENT_PHOTOS (PAYMENT_ID);

-- PROFILE_THEMES
CREATE INDEX SALESAPP.IDX_PT_ROLE_ID ON SALESAPP.PROFILE_THEMES (ROLE_ID, IS_ACTIVE);

-- SALES
CREATE INDEX SALESAPP.IDX_SALES_CUSTOMER  ON SALESAPP.SALES (CUSTOMER_ID);
CREATE INDEX SALESAPP.IDX_SALES_SELLER    ON SALESAPP.SALES (SELLER_ID);
CREATE INDEX SALESAPP.IDX_SALES_COLLECTOR ON SALESAPP.SALES (ASSIGNED_COLLECTOR_ID);
CREATE INDEX SALESAPP.IDX_SALES_DATE      ON SALESAPP.SALES (SALE_DATE);
CREATE INDEX SALESAPP.IDX_SALES_STATUS    ON SALESAPP.SALES (STATUS);
CREATE INDEX SALESAPP.IDX_SALES_STATUS_DATE ON SALESAPP.SALES (STATUS, SALE_DATE DESC);

-- SALE_ITEMS
CREATE INDEX SALESAPP.IDX_SALE_ITEMS_SALE       ON SALESAPP.SALE_ITEMS (SALE_ID);
CREATE INDEX SALESAPP.IDX_SALE_ITEMS_PRODUCT    ON SALESAPP.SALE_ITEMS (PRODUCT_ID);
CREATE INDEX SALESAPP.IDX_SALE_ITEMS_SALE_ORDER ON SALESAPP.SALE_ITEMS (SALE_ID, SALE_ITEM_ID);

-- SALE_PHOTOS
CREATE INDEX SALESAPP.IDX_SALE_PHOTOS_SALE      ON SALESAPP.SALE_PHOTOS (SALE_ID);
CREATE INDEX SALESAPP.IDX_SALE_PHOTOS_SALE_TYPE ON SALESAPP.SALE_PHOTOS (SALE_ID, PHOTO_TYPE);

-- SYNC_QUEUE
CREATE INDEX SALESAPP.IDX_SYNC_USER   ON SALESAPP.SYNC_QUEUE (USER_ID);
CREATE INDEX SALESAPP.IDX_SYNC_SYNCED ON SALESAPP.SYNC_QUEUE (SYNCED);

-- SYNC_CONFLICTS
CREATE INDEX SALESAPP.IDX_CONFLICTS_RESOLVED ON SALESAPP.SYNC_CONFLICTS (RESOLVED);

-- USER_SESSIONS
CREATE INDEX SALESAPP.IDX_SESSIONS_USER ON SALESAPP.USER_SESSIONS (USER_ID);

-- USERS
CREATE INDEX SALESAPP.IDX_USERS_ROLE   ON SALESAPP.USERS (ROLE_ID);
CREATE INDEX SALESAPP.IDX_USERS_ZONE   ON SALESAPP.USERS (ZONE_ID);
CREATE INDEX SALESAPP.IDX_USERS_ACTIVE ON SALESAPP.USERS (IS_ACTIVE);
