-- ===========================================================================
-- VITARAIZ - MIGRACIÓN ESQUEMA SALESAPP
-- Parte 07/09: DATOS — CATÁLOGOS Y SEGURIDAD
-- Tablas: CATALOG_PAYMENT_STATUSES, CATALOG_SALE_STATUSES,
--         CATALOG_RISK_STATUSES, CATALOG_APP_THEMES, CATALOG_APP_SETTINGS,
--         CATALOG_NOTIFICATION_TEMPLATES, ZONES, ROLES, PERMISSIONS,
--         PROFILE_THEMES, ROLE_PERMISSIONS, WHATSAPP_TEMPLATES
-- Generado: 2026-04-03
-- ===========================================================================
SET DEFINE OFF;

-- ---------------------------------------------------------------------------
-- CATALOG_PAYMENT_STATUSES (padres primero, luego hijos)
-- ---------------------------------------------------------------------------
-- Padres (PARENT_STATUS_ID IS NULL)
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (1,'PENDING','WORKFLOW','Pendiente','Pago registrado esperando aprobación',NULL,1,'#FFC107','⏳',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (2,'CONFIRMADO','WORKFLOW','Confirmado','Pago verificado y aplicado al saldo de la venta',NULL,2,'#28A745','✅',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (3,'RECHAZADO','WORKFLOW','Rechazado','Pago rechazado por el supervisor, requiere acción',NULL,3,'#DC3545','❌',1,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (4,'CANCELLED','WORKFLOW','Cancelado','Pago cancelado',NULL,4,'#6C757D','🚫',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (10,'PAGO_RECIBIDO','VISIT_ACTION','Pago Recibido','Cliente realizó un pago',NULL,1,'#28A745','💰',0,1,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (20,'CLIENTE_NO_ENCONTRADO','VISIT_ACTION','Cliente No Encontrado','No se encontró al cliente en la dirección',NULL,2,'#FFC107','🏠',1,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (30,'PROMESA_PAGO','VISIT_ACTION','Promesa de Pago','Cliente promete pagar en fecha específica',NULL,3,'#17A2B8','📅',1,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (40,'CLIENTE_REHUSA','VISIT_ACTION','Cliente Se Rehúsa','Cliente se niega a pagar',NULL,4,'#DC3545','🚫',1,0,1);
-- Hijos
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (21,'CLIENTE_NO_ESTABA','VISIT_ACTION','No estaba en casa','Se tocó o llamó pero nadie atendió en la dirección',20,1,'#FFC107','🏠',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (22,'CLIENTE_MUDADO','VISIT_ACTION','Se mudó / dirección incorrecta','El cliente ya no vive en esa dirección o la dirección es incorrecta',20,2,'#FF5722','📍',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (31,'PROMESA_HOY','VISIT_ACTION','Pasar más tarde hoy','El cliente está pero pide que regresen más tarde el mismo día',30,1,'#17A2B8','🕐',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (32,'PROMESA_MANANA','VISIT_ACTION','Pasar mañana','El cliente promete tener el dinero al día siguiente',30,2,'#17A2B8','📅',0,0,1);
INSERT INTO SALESAPP.CATALOG_PAYMENT_STATUSES (STATUS_ID,STATUS_KEY,STATUS_TYPE,STATUS_NAME,DESCRIPTION,PARENT_STATUS_ID,DISPLAY_ORDER,COLOR_HEX,ICON,REQUIRES_NOTE,REQUIRES_PHOTO,IS_ACTIVE) VALUES (33,'PROMESA_SEMANA','VISIT_ACTION','Próxima semana','El cliente promete pagar la próxima semana',30,3,'#17A2B8','📆',0,0,1);
COMMIT;

-- ---------------------------------------------------------------------------
-- CATALOG_SALE_STATUSES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CATALOG_SALE_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,DISPLAY_ORDER,COLOR_HEX,ICON,IS_ACTIVE) VALUES ('POR_INICIAR','Por Iniciar','Venta registrada pero aún no iniciada',1,'#6C757D','⏳',1);
INSERT INTO SALESAPP.CATALOG_SALE_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,DISPLAY_ORDER,COLOR_HEX,ICON,IS_ACTIVE) VALUES ('EN_PROCESO','En Proceso','Venta activa con pagos pendientes',2,'#28A745','💰',1);
INSERT INTO SALESAPP.CATALOG_SALE_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,DISPLAY_ORDER,COLOR_HEX,ICON,IS_ACTIVE) VALUES ('LIQUIDADO','Liquidado','Venta totalmente pagada',3,'#17A2B8','✅',1);
INSERT INTO SALESAPP.CATALOG_SALE_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,DISPLAY_ORDER,COLOR_HEX,ICON,IS_ACTIVE) VALUES ('CANCELADO','Cancelado','Venta cancelada',4,'#DC3545','❌',1);
INSERT INTO SALESAPP.CATALOG_SALE_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,DISPLAY_ORDER,COLOR_HEX,ICON,IS_ACTIVE) VALUES ('ANULADO','Anulado','Venta anulada por administrador',5,'#FFC107','⚠️',1);
COMMIT;

-- ---------------------------------------------------------------------------
-- CATALOG_RISK_STATUSES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CATALOG_RISK_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,MIN_DAYS,MAX_DAYS,COLOR_HEX,ICON,DISPLAY_ORDER,IS_ACTIVE) VALUES ('VERDE','Verde - Al día','Cliente al día con sus pagos',0,7,'#28A745','🟢',1,1);
INSERT INTO SALESAPP.CATALOG_RISK_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,MIN_DAYS,MAX_DAYS,COLOR_HEX,ICON,DISPLAY_ORDER,IS_ACTIVE) VALUES ('AMARILLO','Amarillo - Atención','Cliente con ligero atraso',8,14,'#FFC107','🟡',2,1);
INSERT INTO SALESAPP.CATALOG_RISK_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,MIN_DAYS,MAX_DAYS,COLOR_HEX,ICON,DISPLAY_ORDER,IS_ACTIVE) VALUES ('ROJO','Rojo - Atrasado','Cliente con atraso significativo',15,21,'#DC3545','🔴',3,1);
INSERT INTO SALESAPP.CATALOG_RISK_STATUSES (STATUS_CODE,STATUS_NAME,DESCRIPTION,MIN_DAYS,MAX_DAYS,COLOR_HEX,ICON,DISPLAY_ORDER,IS_ACTIVE) VALUES ('CRITICO','Crítico - Muy atrasado','Cliente en situación crítica',22,9999,'#6C757D','⚫',4,1);
COMMIT;

-- ---------------------------------------------------------------------------
-- CATALOG_APP_THEMES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CATALOG_APP_THEMES (THEME_CODE,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,BACKGROUND_COLOR,TEXT_COLOR,IS_DEFAULT,IS_ACTIVE) VALUES ('VITARAIZ_DEFAULT','VitaRaiz Verde','#28A745','#20C997','#17A2B8','#F0F4F8','#333333',1,1);
COMMIT;

-- ---------------------------------------------------------------------------
-- CATALOG_APP_SETTINGS
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CATALOG_APP_SETTINGS (SETTING_KEY,SETTING_VALUE,SETTING_TYPE,DESCRIPTION,CATEGORY,IS_PUBLIC) VALUES ('APP_VERSION','1.0.0','STRING','Versión actual de la aplicación','APP',1);
INSERT INTO SALESAPP.CATALOG_APP_SETTINGS (SETTING_KEY,SETTING_VALUE,SETTING_TYPE,DESCRIPTION,CATEGORY,IS_PUBLIC) VALUES ('MAX_PAYMENT_ATTEMPT_DAYS','30','NUMBER','Días máximos para intentar cobrar','COBRANZA',0);
INSERT INTO SALESAPP.CATALOG_APP_SETTINGS (SETTING_KEY,SETTING_VALUE,SETTING_TYPE,DESCRIPTION,CATEGORY,IS_PUBLIC) VALUES ('MIN_PAYMENT_AMOUNT','10','NUMBER','Monto mínimo de pago aceptado','PAGOS',1);
INSERT INTO SALESAPP.CATALOG_APP_SETTINGS (SETTING_KEY,SETTING_VALUE,SETTING_TYPE,DESCRIPTION,CATEGORY,IS_PUBLIC) VALUES ('REQUIRE_PHOTO_FOR_PAYMENT','true','BOOLEAN','Requiere foto para registrar pago','PAGOS',1);
INSERT INTO SALESAPP.CATALOG_APP_SETTINGS (SETTING_KEY,SETTING_VALUE,SETTING_TYPE,DESCRIPTION,CATEGORY,IS_PUBLIC) VALUES ('WHATSAPP_REMINDER_TEMPLATE','PAYMENT_REMINDER','STRING','Template por defecto para recordatorios','NOTIFICACIONES',0);
COMMIT;

-- ---------------------------------------------------------------------------
-- CATALOG_NOTIFICATION_TEMPLATES (MESSAGE_BODY = CLOB)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.CATALOG_NOTIFICATION_TEMPLATES (TEMPLATE_CODE,TEMPLATE_NAME,TEMPLATE_TYPE,SUBJECT,MESSAGE_BODY,VARIABLES,IS_ACTIVE) VALUES ('PAYMENT_CONFIRMATION','Confirmación de Pago','WHATSAPP',NULL,'Hola {CUSTOMER_NAME}, confirmamos tu pago de ${AMOUNT}. Nuevo saldo: ${BALANCE}. ¡Gracias! - VitaRaiz','["CUSTOMER_NAME","AMOUNT","BALANCE"]',1);
INSERT INTO SALESAPP.CATALOG_NOTIFICATION_TEMPLATES (TEMPLATE_CODE,TEMPLATE_NAME,TEMPLATE_TYPE,SUBJECT,MESSAGE_BODY,VARIABLES,IS_ACTIVE) VALUES ('PAYMENT_REMINDER','Recordatorio de Pago','WHATSAPP',NULL,'Hola {CUSTOMER_NAME}, te recordamos que tienes un pago pendiente de ${AMOUNT} con vencimiento el {DUE_DATE}. ¡Gracias por tu preferencia! - VitaRaiz','["CUSTOMER_NAME","AMOUNT","DUE_DATE"]',1);
COMMIT;

-- ---------------------------------------------------------------------------
-- ZONES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.ZONES (ZONE_ID,ZONE_NAME,ZONE_CODE,DESCRIPTION,IS_ACTIVE) VALUES (1,'Zona Norte','ZN','Zona norte de la ciudad','1');
INSERT INTO SALESAPP.ZONES (ZONE_ID,ZONE_NAME,ZONE_CODE,DESCRIPTION,IS_ACTIVE) VALUES (2,'Zona Centro','ZC','Zona centro de la ciudad','1');
INSERT INTO SALESAPP.ZONES (ZONE_ID,ZONE_NAME,ZONE_CODE,DESCRIPTION,IS_ACTIVE) VALUES (3,'Zona Sur','ZS','Zona sur de la ciudad','1');
INSERT INTO SALESAPP.ZONES (ZONE_ID,ZONE_NAME,ZONE_CODE,DESCRIPTION,IS_ACTIVE) VALUES (4,'Zona Este','ZE','Zona este de la ciudad','1');
INSERT INTO SALESAPP.ZONES (ZONE_ID,ZONE_NAME,ZONE_CODE,DESCRIPTION,IS_ACTIVE) VALUES (5,'Zona Oeste','ZO','Zona oeste de la ciudad','1');
COMMIT;

-- ---------------------------------------------------------------------------
-- ROLES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (1,'Vendedora','Captura de ventas en campo','#FF1744','#F8BBD0','#FCE4EC');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (2,'SupervisoraJunior','Supervisión de equipo de ventas','#C62828','#EF9A9A','#FFEBEE');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (3,'SupervisoraSenior','Gestión total de ventas','#C62828','#EF9A9A','#FFEBEE');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (4,'Cobrador','Recolección de pagos','#28A745','#C8E6C9','#E8F5E9');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (5,'SupervisorCobradorJunior','Supervisión equipo cobradores','#28A745','#C8E6C9','#E8F5E9');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (6,'SupervisorCobradorSenior','Gestión total cobranza','#28A745','#C8E6C9','#E8F5E9');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (7,'AdminJunior','Administración operativa','#E91E63','#F8BBD9','#FCE4EC');
INSERT INTO SALESAPP.ROLES (ROLE_ID,ROLE_NAME,ROLE_DESCRIPTION,DEFAULT_THEME_COLOR,DEFAULT_THEME_LIGHT,DEFAULT_THEME_LIGHTER) VALUES (8,'AdminFull','Administrador total sistema','#E91E63','#F8BBD9','#FCE4EC');
COMMIT;

-- ---------------------------------------------------------------------------
-- PERMISSIONS
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (1,'sales.create','ventas','Crear ventas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (2,'sales.view_own','ventas','Ver propias ventas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (3,'sales.view_team','ventas','Ver ventas del equipo');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (4,'sales.view_all','ventas','Ver todas las ventas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (5,'sales.edit_own','ventas','Editar propias ventas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (6,'sales.edit_team','ventas','Editar ventas del equipo');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (7,'sales.annul','ventas','Anular ventas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (8,'payments.register','cobranza','Registrar pagos');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (9,'payments.view_own_accounts','cobranza','Ver cuentas asignadas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (10,'payments.view_totals','cobranza','Ver totales consolidados');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (11,'payments.view_all_totals','cobranza','Ver todos los totales');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (12,'payments.drill_down','cobranza','Drill-down en pagos');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (13,'blacklist.propose','carteras','Proponer lista negra');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (14,'blacklist.approve','carteras','Aprobar lista negra');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (15,'clients.manage_gold','carteras','Gestionar buenos clientes');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (16,'admin.manage_users','admin','Gestionar usuarios');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (17,'admin.configure_themes','admin','Configurar temas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (18,'admin.configure_security','admin','Configurar seguridad');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (19,'admin.view_audit_logs','admin','Ver logs de auditoría');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (21,'customers.view','clientes','Ver clientes');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (22,'customers.create','clientes','Crear clientes');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (23,'customers.edit','clientes','Editar clientes');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (24,'payments.create','cobros','Registrar cobros');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (25,'payments.view','cobros','Ver cobros');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (26,'payments.approve','cobros','Aprobar cobros');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (27,'reports.view','reportes','Ver reportes y estadísticas');
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (28,'COBROS_REGISTRAR','COBROS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (29,'COBROS_APROBAR','COBROS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (30,'COBROS_RECHAZAR','COBROS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (31,'VENTAS_CONSULTAR','VENTAS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (32,'VENTAS_CREAR','VENTAS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (33,'VENTAS_CANCELAR','VENTAS',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (34,'CLIENTES_CONSULTAR','CLIENTES',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (35,'CLIENTES_CREAR','CLIENTES',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (36,'CLIENTES_EDITAR','CLIENTES',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (37,'REPORTES_CONSULTAR','REPORTES',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (38,'ADMIN_USUARIOS','ADMIN',NULL);
INSERT INTO SALESAPP.PERMISSIONS (PERMISSION_ID,PERMISSION_NAME,MODULE,DESCRIPTION) VALUES (39,'ADMIN_CATALOGOS','ADMIN',NULL);
COMMIT;

-- ---------------------------------------------------------------------------
-- PROFILE_THEMES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (1,1,'Tema Ventas','#FF1744','#F8BBD0','#C62828','shopping_cart','#FFF5F5','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (2,2,'Tema Supervisión Jr','#C62828','#EF9A9A','#8E0000','supervisor_account','#FFF5F5','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (3,3,'Tema Supervisión Sr','#8E0000','#FFCDD2','#C62828','verified_user','#FAFAFA','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (4,4,'Tema Cobranza','#00C853','#B9F6CA','#00A152','account_balance_wallet','#FAFAFA','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (5,5,'Tema Sup. Cobranza Jr','#00A152','#C8E6C9','#00701A','manage_accounts','#FAFAFA','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (6,6,'Tema Sup. Cobranza Sr','#00701A','#A5D6A7','#00C853','account_balance','#FAFAFA','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (7,7,'Tema Admin Jr','#2196F3','#BBDEFB','#1565C0','settings','#FAFAFA','#333333',1);
INSERT INTO SALESAPP.PROFILE_THEMES (THEME_ID,ROLE_ID,THEME_NAME,PRIMARY_COLOR,SECONDARY_COLOR,ACCENT_COLOR,ICON_NAME,BACKGROUND_COLOR,TEXT_COLOR,IS_ACTIVE) VALUES (8,8,'Tema Admin Full','#0D47A1','#90CAF9','#2196F3','admin_panel_settings','#FAFAFA','#333333',1);
COMMIT;

-- ---------------------------------------------------------------------------
-- ROLE_PERMISSIONS (88 registros)
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (1,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (1,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (1,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (2,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (3,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (4,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (4,28);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (4,31);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (4,34);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (5,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (6,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,4);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,8);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,9);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,10);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,11);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,12);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,13);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,14);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,15);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,16);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,17);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,18);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (7,19);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,1);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,2);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,3);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,4);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,5);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,6);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,7);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,8);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,9);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,10);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,11);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,12);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,13);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,14);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,15);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,16);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,17);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,18);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,19);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,21);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,22);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,23);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,24);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,25);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,26);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,27);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,28);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,29);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,30);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,31);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,32);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,33);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,34);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,35);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,36);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,37);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,38);
INSERT INTO SALESAPP.ROLE_PERMISSIONS (ROLE_ID,PERMISSION_ID) VALUES (8,39);
COMMIT;

-- ---------------------------------------------------------------------------
-- WHATSAPP_TEMPLATES
-- ---------------------------------------------------------------------------
INSERT INTO SALESAPP.WHATSAPP_TEMPLATES (TEMPLATE_ID,TEMPLATE_NAME,TEMPLATE_BODY,VARIABLES,IS_ACTIVE) VALUES (1,'PAYMENT_RECEIPT','¡Hola {customer_name}! Confirmamos tu pago de ${amount} el día {payment_date}. Tu saldo restante es ${remaining_balance}. ¡Gracias por tu puntualidad! 🙏','customer_name,amount,payment_date,remaining_balance','1');
INSERT INTO SALESAPP.WHATSAPP_TEMPLATES (TEMPLATE_ID,TEMPLATE_NAME,TEMPLATE_BODY,VARIABLES,IS_ACTIVE) VALUES (2,'PAYMENT_REMINDER','Hola {customer_name}, te recordamos que tu próximo pago de ${amount} vence el {due_date}. ¡Contamos contigo! 😊','customer_name,amount,due_date','1');
INSERT INTO SALESAPP.WHATSAPP_TEMPLATES (TEMPLATE_ID,TEMPLATE_NAME,TEMPLATE_BODY,VARIABLES,IS_ACTIVE) VALUES (3,'LATE_PAYMENT_NOTICE','Estimado/a {customer_name}, detectamos que tienes {days_late} días de atraso en tu pago. Por favor comunícate con nosotros para regularizar tu situación. Saldo pendiente: ${remaining_balance}','customer_name,days_late,remaining_balance','1');
COMMIT;

SET DEFINE ON;
